### ISSUE TITLE
Failure to Generate

### ISSUE THREAD

**Issue by mekhami** [chopdgd/cookiecutter-django-reactjs#12]
## What happened?
```
project_name [My Awesome Project]: ...
project_slug [...]:
description [Behold My Awesome Project!]: ...
author_name [Daniel Roy Greenfeld]: ...
domain_name [example.com]: ...
email [...@example.com]: ...
version [0.1.0]:
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 (1, 2, 3, 4, 5) [1]:
timezone [UTC]: America/Chicago
windows [n]:
use_pycharm [n]:
use_docker [n]: y
Select postgresql_version:
1 - 11.3
2 - 10.8
3 - 9.6
4 - 9.5
5 - 9.4
Choose from 1, 2, 3, 4, 5 (1, 2, 3, 4, 5) [1]: 1
Select js_task_runner:
1 - None
2 - CreateReactApp
3 - Gulp
Choose from 1, 2, 3 (1, 2, 3) [1]:
Select cloud_provider:
1 - AWS
2 - GCP
3 - None
Choose from 1, 2, 3 (1, 2, 3) [1]: 3
custom_bootstrap_compilation [n]:
use_compressor [n]:
use_celery [n]: y
use_mailhog [n]: y
use_sentry [n]: y
use_whitenoise [n]: y
use_heroku [n]: n
use_travisci [n]: n
keep_local_envs_in_vcs [y]: n
debug [n]:
Traceback (most recent call last):
  File "/var/folders/k9/r3vrd5ys6137jlm8fb4mmcfc0000gn/T/tmp8wrgffr0.py", line 382, in <module>
    main()
  File "/var/folders/k9/r3vrd5ys6137jlm8fb4mmcfc0000gn/T/tmp8wrgffr0.py", line 359, in main
    remove_react_files()
  File "/var/folders/k9/r3vrd5ys6137jlm8fb4mmcfc0000gn/T/tmp8wrgffr0.py", line 106, in remove_react_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '<myproject>/templates/index.html'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

## What should've happened instead?

Successful Project Generation

## Steps to reproduce

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.) OS X host
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by mekhami** [comment]
Turns out "CreateReactApp" is required; may as well edit the cookiecutter to remove that step and make it the default.
