### ISSUE TITLE
rest_framework missing from requirements file

### ISSUE THREAD

**Issue by Moataz-E** [chopdgd/cookiecutter-django-reactjs#23]
## What happened?

After installing all the required libraries using pip, I get the following error:

`Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/home/moataz/projects/efhass/code/venv_efhass/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/moataz/projects/efhass/code/venv_efhass/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/moataz/projects/efhass/code/venv_efhass/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/moataz/projects/efhass/code/venv_efhass/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/moataz/projects/efhass/code/venv_efhass/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'`

## What should've happened instead?

After inspecting the requirements/local.txt and requirements/base.txt files, I was unable to find a line corresponding to the rest_framework library.

**Comment by Moataz-E** [comment]
The issue is because I didn't choose **y** for the `use_drf` option when creating the project using cookiecutter. My recommendation is for that option to be **y** by default given this is a requirement for the project to work.
